import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import type { AdminHealth } from "../adminApi";
import Icon from "./SystemAtlasIcon";
import type { AtlasArchitecture, AtlasSnapshot } from "./systemAtlasApi";
import type { MonitorView } from "./AtlasMonitoring";
import { actionLabel, behaviorRecords, sessionLabel, DOMAIN_COLORS, DOMAIN_NAMES, FLOW_HEIGHT, FLOW_WIDTH, flowPositions, flowRecords, callDestination, UNIT_COLORS, type FlowRecord, type FlowState } from "./atlasFlowModel";
import AtlasSessionWatch from "./AtlasSessionWatch";
import type { NexusQuality } from "./atlasNexusWorld";
import "./atlasNexus.css";

const ms = (n?: number | null) => n == null ? "—" : n >= 1000 ? `${(n / 1000).toFixed(2)}s` : `${Math.round(n)}ms`;
const num = (n?: number | null) => n == null ? "—" : n.toLocaleString("ko-KR");
const SERVICE_FORMS: Record<string, [string, string]> = { market:["MARKET / PRICE ENGINE","시세 · 지수 · 수급"], community:["NEWS / INFORMATION STREAM","뉴스 · 번역 · 커뮤니티"], realestate:["ESTATE / SPATIAL ENGINE","지도 · 단지 · 실거래"], prediction:["AI / INFERENCE CORE","분석 · 예측 · 학습"], operations:["OPS / CONTROL ENGINE","관리 · 배치 · 모니터링"], support:["SUPPORT / ENERGY CORE","후원 · 결제 · 응원"] };
type JournalLine = { key:string; at:number; type:"user"|"request"|"http"|"depart"|"arrival"; source:string; target:string; detail:string; color:string; status:string; record:FlowRecord; fault:boolean };
const logTime=(n:number)=>new Date(n*1000).toLocaleTimeString("ko-KR",{hour12:false});
const tint = (color: string) => ({ "--af-color": color } as CSSProperties);
type Props = { graph: AtlasArchitecture; live: AtlasSnapshot | null; health: AdminHealth | null; selected: string; onSelect: (id: string) => void; onView: (view: MonitorView, filter?: string) => void; paused: boolean; stale: boolean; healthStale: boolean };
export default function AtlasNexus({ graph, live, selected, onSelect, onView, paused, stale, healthStale }: Props) {
  const domain = graph.nodes.some(n => n.id === selected && n.kind === "service") ? selected : "gateway";
  const host = useRef<HTMLDivElement>(null), scroll = useRef<HTMLDivElement>(null), world = useRef<{ invalidate: () => void; dispose: () => void } | null>(null);
  const [quality, setQuality] = useState<NexusQuality>(() => innerWidth < 700 ? "balanced" : "cinematic"), [speed, setSpeed] = useState(3), [motion, setMotion] = useState(true);
  const [ready, setReady] = useState(false), [failure, setFailure] = useState(false), [retry, setRetry] = useState(0), [replay, setReplay] = useState(0), [focus, setFocus] = useState<string | null>(null);
  const [mode, setMode] = useState<"users" | "system">("users"), [session, setSession] = useState<string | null>(null);
  const [logs, setLogs] = useState<JournalLine[]>([]), crawlSerial=useRef(0), logSeen=useRef(new Set<string>()), journal=useRef<HTMLDivElement>(null), stick=useRef(true), [follow,setFollow]=useState(true), [reduced, setReduced] = useState(() => matchMedia("(prefers-reduced-motion: reduce)").matches);
  const current = useRef<FlowState>({ live, selected: domain, focus, replay, motion, reduced, speed, mode, session }); current.current = { live, selected: domain, focus, replay, motion: motion && !paused, reduced, speed, mode, session };
  useEffect(() => { const media = matchMedia("(prefers-reduced-motion: reduce)"); const change = () => setReduced(media.matches); media.addEventListener("change", change); return () => media.removeEventListener("change", change); }, []);
  useEffect(() => {
    let gone = false; setReady(false); setFailure(false);
    import("./atlasNexusWorld").then(({ createNexusWorld }) => { if (gone || !host.current) return; try { world.current = createNexusWorld(host.current, graph, quality, () => current.current, event => { if (!gone && current.current.mode === "system") { const r=event.record;const key=`crawl:${++crawlSerial.current}`;setLogs(prev=>[...prev,{key,at:Date.now()/1000,type:event.kind,source:`거미 W-0${event.unit+1}`,target:DOMAIN_NAMES[event.target]||graph.nodes.find(n=>n.id===event.target)?.label.split(" · ")[0]||"배치 HTTP",detail:r.request.route||r.request.host||"",color:r.fault?"#ff809e":DOMAIN_COLORS[r.group]||UNIT_COLORS[event.unit],status:event.kind==="arrival"?"도착 · 거미줄 확산":"경로 이동",record:r,fault:r.fault}].slice(-100)); } }, () => { if (!gone) setRetry(n => n + 1); }); setReady(true); } catch { host.current?.replaceChildren(); setFailure(true); } }).catch(() => { if (!gone) setFailure(true); });
    return () => { gone = true; world.current?.dispose(); world.current = null; };
  }, [graph, quality, retry]);
  useEffect(() => { world.current?.invalidate(); }, [live, selected, focus, replay, motion, paused, reduced, speed, mode, session]);
  const records = useMemo(() => flowRecords(graph, live, mode, session), [graph, live, mode, session]), points = useMemo(() => flowPositions(graph), [graph]);
  const userRecords = useMemo(() => behaviorRecords(live, session, 900), [live, session]);
  const userLogs: JournalLine[] = [...userRecords].reverse().slice(-100).map(r => ({ key: r.key, at: r.request.ts, type: "user", source: sessionLabel(r.session!), target: DOMAIN_NAMES[r.group], detail: actionLabel(r.action!), color: DOMAIN_COLORS[r.group], status: r.action!.type === "page_view" ? "이동" : "행동", record: r, fault: false }));
  const visibleLogs = mode === "users" ? userLogs : logs;
  const behaviorCounts = records.reduce<Record<string, number>>((counts, r) => { counts[r.group] = (counts[r.group] || 0) + 1; return counts; }, {});
  const count = (id?: string) => mode === "users" ? id ? behaviorCounts[id] || 0 : records.length : id ? live?.api.groups[id]?.count || 0 : live?.api.count;
  const watchSession = (id: string | null) => { setSession(id); setMode("users"); setFocus(null); onSelect("gateway"); };
  const services = graph.nodes.filter(n => n.kind === "service"), destinationNodes = graph.nodes.filter(n => points[n.id] && n.kind !== "service" && n.id !== "gateway");
  useEffect(()=>{
    if (mode !== "system") return;
    const fresh:JournalLine[]=[];
    for(const r of [...records].reverse()) {
      if(!r.batch && !logSeen.current.has(r.key)) { logSeen.current.add(r.key);fresh.push({key:r.key,at:r.request.ts,type:"request",source:"API GATEWAY",target:DOMAIN_NAMES[r.group],detail:`${r.request.method} ${r.request.route}`,color:DOMAIN_COLORS[r.group],status:`${r.request.status||"ERR"} · ${ms(r.request.ms)}`,record:r,fault:!r.request.status||r.request.status>=500}); }
      for(const c of r.calls) { const key=`http:${c.id}:${c.ts}`;if(logSeen.current.has(key))continue;logSeen.current.add(key);const target=callDestination(graph,c);fresh.push({key,at:c.ts,type:"http",source:r.batch?"BATCH HTTP":DOMAIN_NAMES[r.group],target:graph.nodes.find(n=>n.id===target)?.label.split(" · ")[0]||c.host||"HTTP",detail:`${c.method} ${c.host}${c.route||""}`,color:DOMAIN_COLORS[r.group]||"#b4a1ff",status:`${c.status||"ERR"} · ${ms(c.ms)}`,record:r,fault:!c.status||c.status>=500}); }
    }
    if(fresh.length) setLogs(prev=>[...prev,...fresh.sort((a,b)=>a.at-b.at)].slice(-100));
    if(logSeen.current.size>2000) logSeen.current=new Set(records.flatMap(r=>[r.key,...r.calls.map(c=>`http:${c.id}:${c.ts}`)]));
  },[records,graph,mode]);
  useEffect(()=>{if(stick.current && journal.current) journal.current.scrollTop=journal.current.scrollHeight;},[logs,live,mode,session]);
  const service = services.find(n => n.id === domain), scoped = records.filter(r => domain === "gateway" || r.group === domain), chosen = (mode === "users" ? userRecords : scoped).find(r => r.key === focus) || scoped.find(r => !r.batch && r.calls.length > 0) || scoped.find(r => !r.batch) || scoped[0];
  const stats = service ? live?.api.groups[service.id] : live?.api;
  const pick = (id: string) => { onSelect(id); setFocus(null); const point = points[id]; if (scroll.current && point && scroll.current.scrollWidth > scroll.current.clientWidth) scroll.current.scrollTo({ left: point.x / FLOW_WIDTH * scroll.current.scrollWidth - scroll.current.clientWidth / 2, behavior: reduced ? "auto" : "smooth" }); };
  const maxCalls = Math.max(1, ...services.map(n => count(n.id) || 0));
  const timeline = live?.api.breakdown?.timeline || [];
  return <section className={`af-command ${failure ? "is-fallback" : ""} ${paused || reduced || !motion ? "is-paused" : ""}`} aria-label="거미 트래픽 관제">
    <header className="af-command-head"><div><p className="af-eyebrow"><i/>ATLAS / LIVING NETWORK</p><h1>TRAFFIC <span>ALIVE.</span></h1><p className="af-subtitle">접속 세션의 실제 행동을 따라가는 거미 관제.</p></div><div className="af-controls"><label>관찰 대상<select aria-label="거미 관찰 대상" value={mode} onChange={e => { setMode(e.target.value as "users" | "system"); setSession(null); setFocus(null); onSelect("gateway"); }}><option value="users">사용자 행동</option><option value="system">시스템 진단</option></select></label><label>이동 속도<select aria-label="거미 이동 속도" value={speed} onChange={e => setSpeed(Number(e.target.value))}><option value={1}>차분하게</option><option value={3}>활발하게</option><option value={5}>빠르게</option></select></label><label>그래픽<select aria-label="3D 그래픽 품질" value={quality} onChange={e => setQuality(e.target.value as NexusQuality)}><option value="cinematic">시네마틱</option><option value="balanced">균형</option><option value="eco">절전</option></select></label><button onClick={() => setMotion(m => !m)} disabled={reduced} aria-pressed={!motion}><Icon name={motion ? "pause" : "play"} size={14}/>{reduced ? "모션 감소" : motion ? "모션 정지" : "모션 재개"}</button><button className="af-replay" disabled={!scoped.length} onClick={() => setReplay(n => n + 1)}><Icon name="play" size={14}/>표본 재생</button></div></header>
    <AtlasSessionWatch live={live} selected={session} onSelect={watchSession} paused={paused} stale={stale}/>
    <div className="af-kpis">
      <button style={tint("#55d9ff")} onClick={() => mode === "users" ? watchSession(null) : onView("api")}><span>{mode === "users" ? "USER ACTIONS" : "API THROUGHPUT"} <Icon name="gateway" size={17}/></span><strong>{mode === "users" ? num(count()) : live ? (live.api.count / 60).toFixed(2) : "—"}<small>{mode === "users" ? "행동 / 60s" : "req/s"}</small></strong><footer><span>{mode === "users" ? session ? sessionLabel(session) : "전체 접속 세션의 행동" : `최근 60초 ${num(live?.api.count)}건`}</span>{mode === "system" && <div className="af-spark-bars">{timeline.map((b, i) => <i key={i} style={{ height: `${Math.max(8, b.count / Math.max(1, ...timeline.map(t => t.count)) * 100)}%` }}/>)}</div>}</footer></button>
      <button style={tint("#bc9bff")} onClick={() => mode === "users" ? watchSession(null) : onView("external")}><span>{mode === "users" ? "PAGE JOURNEYS" : "EXTERNAL LINKS"} <Icon name="external" size={17}/></span><strong>{num(mode === "users" ? records.filter(r => r.action?.type === "page_view").length : live?.external.count)}<small>{mode === "users" ? "이동 / 60s" : "calls / 60s"}</small></strong><footer><span>{mode === "users" ? "실제 페이지 이동" : `${num(live?.external.hosts.length)}개 관측 호스트`}</span><b>{mode === "users" ? "방문 집계 제외" : `${num(live?.external.errors)} 실패`}</b></footer></button>
      <button style={tint("#ffbd77")} onClick={() => mode === "users" ? watchSession(null) : onView("api", "slow")}><span>{mode === "users" ? "CONNECTED SESSIONS" : "RESPONSE LATENCY"} <Icon name="cache" size={17}/></span><strong>{mode === "users" ? num(live?.behavior?.online_count) : ms(live?.api.p95_ms)}<small>{mode === "users" ? "접속 확인" : "P95"}</small></strong><footer><span>{mode === "users" ? "최근 120초 접속 신호" : `P50 ${ms(live?.api.p50_ms)}`}</span><b>{mode === "users" ? `${num(live?.behavior?.active_count)} 행동 세션` : `${num(live?.api.slow)} 느린 응답`}</b></footer></button>
      <button style={tint("#ff8499")} onClick={() => onView("api", "errors")}><span>ATTENTION SIGNALS <Icon name="info" size={17}/></span><strong>{num(live ? live.api.errors + live.external.errors : null)}<small>실패 표본</small></strong><footer><span>API {num(live?.api.errors)} · HTTP {num(live?.external.errors)}</span><b>{paused ? "관측 정지" : stale || healthStale ? "갱신 지연" : "OBSERVING"}</b></footer></button>
    </div>
    <div className={`af-workspace ${mode === "users" ? "af-user-mode" : ""}`}><section className="af-flow-panel"><header className="af-flow-head"><div><span className="af-live-dot"/><h2>{mode === "users" ? session ? `${sessionLabel(session)} 행동 경로` : "전체 사용자 행동 경로" : "서비스 데이터 흐름"}</h2><span>최근 60초 관측 표본</span></div><div className="af-legend"><i/>{mode === "users" ? "행동" : "요청"} <i/>{mode === "users" ? "이동" : "응답"} <i/>오류</div></header>
      <div className="af-domain-tabs" role="group" aria-label="관제 서비스 선택"><button aria-pressed={domain === "gateway"} onClick={() => pick("gateway")}>전체 흐름 <b>{num(count())}</b></button>{services.map(n => <button key={n.id} style={tint(DOMAIN_COLORS[n.id])} aria-pressed={selected === n.id} onClick={() => pick(n.id)}><i/>{DOMAIN_NAMES[n.id]}<b>{num(count(n.id))}</b></button>)}</div>
      <div className="af-flow-scroll" ref={scroll}><div className="af-flow-stage">
        <div className="af-stage-guides" aria-hidden="true"><span>01 / REQUEST GATEWAY</span><span>02 / SERVICE LANDMARKS</span><span>03 / HTTP TERMINALS</span></div>
        <div className="af-scene" ref={host}/>
        {(!ready || failure) && <div className="af-scene-status" role="status"><Icon name="atlas" size={32}/><h3>{failure ? "데이터 관제 모드" : "거미 관제 연결 중"}</h3>{failure && <><p>그래픽 연결을 사용할 수 없습니다. 서비스 지표와 요청 분석은 계속 이용할 수 있습니다.</p><button onClick={() => setRetry(n => n + 1)}>그래픽 다시 연결</button></>}</div>}
        <div className="af-context-note" role="status">그래픽 연결 복구 중</div>
        <button data-flow-node="gateway" className="af-gateway" onClick={() => pick("gateway")} style={{ left: `${points.gateway.x / FLOW_WIDTH * 100}%`, top: `${points.gateway.y / FLOW_HEIGHT * 100}%` }}><small>{mode === "users" ? "USER ACTIONS" : "API GATEWAY"}</small><b>{num(count())}</b><span>{mode === "users" ? "ACTIONS / 60s" : "REQUESTS / 60s"}</span></button>
        <div className="af-ingress" style={{ top: `${points.ingress.y / FLOW_HEIGHT * 100}%` }}><span>IN</span><i/><small>API</small></div>
        <div data-flow-node="batch" className="af-batch" style={{ left: `${points.batch.x / FLOW_WIDTH * 100}%`, top: `${points.batch.y / FLOW_HEIGHT * 100}%` }}><Icon name="refresh" size={16}/><b>배치 HTTP</b><span>요청 문맥 없는 외부 호출</span></div>
        {services.map(n => { const s=live?.api.groups[n.id],p=points[n.id],form=SERVICE_FORMS[n.id];return <button key={n.id} data-flow-node={n.id} className={`af-service-node af-node-${n.id} ${selected===n.id?"is-selected":""} ${s?.errors?"has-error":""} ${domain!=="gateway"&&domain!==n.id?"is-dim":""}`} style={{...tint(DOMAIN_COLORS[n.id]),left:`${p.x/FLOW_WIDTH*100}%`,top:`${(p.y+75)/FLOW_HEIGHT*100}%`}} onClick={()=>pick(n.id)} aria-label={`${DOMAIN_NAMES[n.id]} 흐름 선택`} aria-pressed={selected===n.id}><small className="af-service-kicker">{form[0]}</small><div className="af-service-title"><Icon name={n.id} size={18}/><b>{DOMAIN_NAMES[n.id]}</b><i className={s?.errors?"is-error":""}/></div><div className="af-node-metrics"><strong>{num(count(n.id))}<small>{mode === "users" ? "ACTIONS" : "REQUESTS"}</small></strong>{mode === "system" && <span>P95 <b>{ms(s?.p95_ms)}</b></span>}</div><span className="af-node-caption">{form[1]}</span></button>;})}
        {destinationNodes.map((n,i)=>{const p=points[n.id],s=live?.external.groups[n.id];return <button key={n.id} data-flow-node={n.id} className={`af-destination ${n.kind==="storage"?"is-database":"is-http"} ${s?.errors?"has-error":""}`} style={{...tint(n.color),left:`${p.x/FLOW_WIDTH*100}%`,top:`${p.y/FLOW_HEIGHT*100}%`}} onClick={()=>{onSelect(n.id);onView(n.kind==="storage"?"storage":"external");}}><span className="af-terminal-port">{n.kind==="storage"?"DB":"HTTP"}<i/></span><div><small>PORT {String(i+1).padStart(2,"0")}</small><b>{n.label.split(" · ")[0]}</b><span>{n.id==="ext-ai"?"CLI / SDK · 관측 범위 밖":n.id==="ext-pay"?"결제 사이트 이동":s?.count?`${s.count} HTTP · ${ms(s.p95_ms)}`:"HTTP 표본 없음"}</span></div></button>;})}
        <div className="af-stage-foot"><span>입체 경로 · 서비스별 색상</span><span>{mode === "users" ? "빛 신호 = 실제 관측 행동 재생" : "빛 신호 = 관측된 요청 / 응답 재생"}</span></div>
      </div></div><footer className="af-flow-footer"><span><Icon name="trace" size={13}/>{mode === "users" ? "페이지 이동과 선택을 재생하고 새 행동에 우선 반응합니다. 대기 순찰은 화면 동작이며 행동·로그 집계에 포함하지 않습니다." : "완료 요청을 압축 재생합니다. 동일 표본을 중복 재생하지 않으며, 대기 순찰은 요청·도착·로그를 생성하지 않습니다."}</span><b className="af-mobile-hint">좌우로 흐름 탐색 ↔</b></footer>
    </section><aside className="af-ops-panel af-journal"><header><span><i/>FLOW JOURNAL</span><b>{paused ? "PAUSED" : "LIVE STREAM"}</b></header><h2>실시간 흐름 로그</h2><p>{mode === "users" ? session ? `${sessionLabel(session)} · 실제 행동만 표시` : "전체 접속 세션 · 실제 행동만 표시" : "시스템 진단 · API / HTTP / 거미 재생"}</p>
      <div className="af-journal-toolbar"><span><b>{visibleLogs.length}</b> EVENTS / 최대 100</span><button aria-pressed={follow} onClick={() => { stick.current = !follow; setFollow(!follow); if (!follow && journal.current) journal.current.scrollTop = journal.current.scrollHeight; }}>{follow ? "자동 스크롤 ON" : "자동 스크롤 OFF"}<Icon name="arrow" size={11}/></button></div>
      <div className="af-log-stream" ref={journal} role="log" aria-label="트래픽 흐름 로그" aria-live="off" onWheel={() => { stick.current = false; setFollow(false); }} onTouchMove={() => { stick.current = false; setFollow(false); }}>{visibleLogs.length ? visibleLogs.map(line => <button key={line.key} className={`af-log-line af-log-${line.type} ${line.fault ? "has-error" : ""}`} style={tint(line.color)} onClick={() => { if (line.record.session) watchSession(line.record.session); else { pick(line.record.batch ? "gateway" : line.record.group); setFocus(line.record.key); } }}>
        <header><time>{logTime(line.at)}</time><b>{line.type === "user" ? "USER" : line.type === "request" ? "REQ" : line.type === "http" ? "HTTP" : line.type === "arrival" ? "ARRIVED" : "CRAWL"}</b><span>{line.status}</span></header><div><span>{line.source}</span><Icon name="arrow" size={11}/><strong>{line.target}</strong></div><code>{line.detail}</code></button>) : <div className="af-log-wait"><i/><b>{mode === "users" ? "USER ACTIVITY LISTENING" : "TRAFFIC LISTENING"}</b><span>{mode === "users" ? "사용자의 이동과 선택이 관측되면 표시됩니다." : "요청이 관측되면 흐름이 누적됩니다."}</span></div>}<span className="af-log-cursor" aria-hidden="true">▌</span></div><footer className="af-journal-foot"><i/><span>{stale ? "관측 갱신 지연" : paused ? "관측 일시 정지" : mode === "users" ? "페이지 이동 · 선택 · 종목 조회" : "현재 화면에서 시스템 기록 누적 중"}</span><b>1 SPIDER / 8 LEGS</b></footer></aside></div>
    <div className="af-analysis"><section className="af-service-load"><header><h2>{service ? `${DOMAIN_NAMES[service.id]} 관측` : mode === "users" ? "서비스별 사용자 행동" : "서비스별 트래픽"}</h2><button onClick={() => onView(service ? "services" : "overview")}>상세 분석<Icon name="arrow" size={13}/></button></header>{services.map(n => <button key={n.id} style={tint(DOMAIN_COLORS[n.id])} className={selected === n.id ? "is-selected" : ""} onClick={() => pick(n.id)}><span>{DOMAIN_NAMES[n.id]}</span><div><i style={{ width: `${(count(n.id) || 0) / maxCalls * 100}%` }}/></div><b>{num(count(n.id))}</b><small>{mode === "users" ? "행동" : ms(live?.api.groups[n.id]?.p95_ms)}</small></button>)}<p>{mode === "users" ? `최근 60초 · ${session ? sessionLabel(session) : "전체 세션"} · 실제 관측 행동` : `선택 영역: ${num(stats?.count)}건 · P95 ${ms(stats?.p95_ms)} · 실패 ${num(stats?.errors)}`}</p></section>
    {mode === "users" ? <section className="af-trace-panel"><header><div><span>USER JOURNEY</span><h2>{chosen?.session ? sessionLabel(chosen.session) : "사용자 행동 대기"}</h2></div>{session && <button onClick={() => watchSession(null)}>전체 세션<Icon name="arrow" size={13}/></button>}</header>{chosen?.action ? <><div className="af-user-action"><time>{logTime(chosen.request.ts)}</time><strong>{actionLabel(chosen.action)}</strong><code>{chosen.action.path}</code></div><div className="af-request-steps"><span><Icon name="client" size={17}/>접속 세션</span><Icon name="arrow" size={14}/><span style={tint(DOMAIN_COLORS[chosen.group])}><Icon name={chosen.group} size={17}/>{DOMAIN_NAMES[chosen.group]}</span></div><footer><span>실제 브라우저 행동 표본 · API 호출과 별도 관측</span><button onClick={() => watchSession(chosen.session!)}>이 세션 관찰<Icon name="trace" size={12}/></button></footer></> : <p className="af-empty">사용자의 페이지 이동이나 선택이 발생하면 표시됩니다.</p>}</section> : <section className="af-trace-panel"><header><div><span>REQUEST REPLAY</span><h2>{chosen ? chosen.batch ? "배치 HTTP 경로" : `요청 #${chosen.request.trace_id || chosen.request.id}` : "요청 표본 대기"}</h2></div><button onClick={() => onView("traces")}>요청 추적<Icon name="arrow" size={13}/></button></header><div className="af-trace-chips">{scoped.slice(0, 12).map(r => <button key={r.key} onClick={() => { setFocus(r.key); setReplay(n => n + 1); }} aria-pressed={chosen?.key === r.key} className={r.fault ? "has-error" : ""}>#{r.request.trace_id || r.request.id}<b>{r.request.status || "ERR"}</b></button>)}</div>{chosen ? <><div className="af-request-route"><span>{chosen.request.method}</span><code>{chosen.request.route || chosen.request.host}</code><b className={chosen.fault ? "af-error" : ""}>{ms(chosen.request.ms)}</b></div><div className="af-request-steps"><span><Icon name={chosen.batch ? "refresh" : "gateway"} size={17}/>{chosen.batch ? "배치" : "API"}</span><Icon name="arrow" size={14}/><span style={tint(DOMAIN_COLORS[chosen.group] || "#bc9bff")}><Icon name={chosen.group} size={17}/>{DOMAIN_NAMES[chosen.group] || "HTTP 호출"}</span><Icon name="arrow" size={14}/><div>{chosen.calls.length ? chosen.calls.map(c => <span key={c.id} className={!c.status || c.status >= 500 ? "af-error" : ""}><Icon name="external" size={13}/><code>{c.host}</code><b>{c.status || "ERR"} · {ms(c.ms)}</b></span>) : <span>연결된 외부 HTTP 표본 없음</span>}</div></div><footer><span>{chosen.calls.length}개 연결 HTTP 표본{live?.traces?.find(t => t.request.id === chosen.request.id)?.calls_truncated ? " · 일부 생략" : ""}</span><button onClick={() => setReplay(n => n + 1)}>이 요청 재생<Icon name="play" size={12}/></button></footer></> : <p className="af-empty">요청이 완료되면 서비스와 외부 HTTP의 연결 과정이 표시됩니다.</p>}</section>}</div>
    <footer className="af-coverage"><span>현재 프로세스 · 거미 경로 60초 / 세션 도표 15분 · 실제 관측 행동 재생</span><span>SQL·SDK·브라우저 직접 호출 미포함 <button onClick={() => onView("stack")}>관측 범위<Icon name="arrow" size={12}/></button></span></footer>
  </section>;
}
