import { useEffect } from "react";

/* ============================================================================
   Driving the equaliser from the actual music.
   ----------------------------------------------------------------------------
   The bars move to the real track — the same peaks, the same quiet passages —
   without anything analysing audio in the browser, because nothing in the
   browser can. The sound comes out of a cross-origin YouTube iframe and the Web
   Audio API has no way to reach into one; there is no element to hand to
   createMediaElementSource and no way to obtain one.

   What IS reachable is the playback position. So the analysis happened once,
   offline (backend/scripts/bgm_envelope.py), and this reads the answer at the
   right moment: `getCurrentTime()` gives a second, that second gives a frame,
   and the frame gives fourteen levels.

   Two things about how it writes them:

   - Straight to the DOM, not through React state. Fourteen bars at twenty
     frames a second is 280 updates a second; through state that is 280 renders
     of a component that also owns the index tickers and the whole HUD.

   - At the envelope's own rate, not the screen's. There is no more data
     between frames, so a 60 Hz loop would write the same numbers three times
     over. A CSS transition covers the gap instead, which puts the smoothing on
     the compositor where it costs nothing.
   ========================================================================= */

interface Envelope {
  fps: number;
  bands: number;
  duration: number;
  data: string;
}

/** One fetch per track for the life of the page. The files are static and a
 * visitor may well switch between the same two tracks all afternoon. */
const cache = new Map<string, Envelope | null>();

async function loadEnvelope(trackId: string): Promise<Envelope | null> {
  const cached = cache.get(trackId);
  if (cached !== undefined) return cached;
  try {
    const res = await fetch(`/bgm/${trackId}.json`);
    if (!res.ok) throw new Error(`${res.status}`);
    const doc = (await res.json()) as Envelope;
    // A malformed or truncated file must not be allowed to drive anything; the
    // decorative fallback is a much better outcome than a row of dead bars.
    if (!doc?.data || !doc.bands || !doc.fps) throw new Error("malformed envelope");
    cache.set(trackId, doc);
    return doc;
  } catch (error) {
    // Remembered as "no envelope" so a missing file is not re-fetched every
    // time the track comes round again.
    cache.set(trackId, null);
    console.warn(`[bgm] no envelope for ${trackId}, using the decorative bars`, error);
    return null;
  }
}

/** base36 in, 0..1 out. '0'-'9' then 'a'-'z' — see bgm_envelope.py. */
function levelOf(code: number): number {
  // 48 is '0', 97 is 'a'. Digits are 0-9; letters continue from 10.
  const value = code < 58 ? code - 48 : code - 87;
  return value / 35;
}

export function useBgmEqualizer(
  containerRef: React.RefObject<HTMLElement>,
  trackId: string | null,
  playing: boolean,
  getTime: () => number | null
): void {
  useEffect(() => {
    const container = containerRef.current;
    if (!container || !playing || !trackId) return;

    let stopped = false;
    let timer: number | undefined;

    loadEnvelope(trackId).then((envelope) => {
      if (stopped || !envelope) return;
      const bars = Array.from(container.children) as HTMLElement[];
      if (bars.length === 0) return;

      // The envelope may carry a different band count than the page draws —
      // it is generated by a script with its own constant. Reading the lesser
      // of the two means a mismatch shows as bars that do not move rather than
      // as an exception.
      const used = Math.min(bars.length, envelope.bands);
      const lastFrame = Math.floor(envelope.data.length / envelope.bands) - 1;

      // Hands the bars over from the CSS animation to us. Without this the
      // keyframes keep overwriting the transform and nothing appears to
      // happen — an animation beats an inline style.
      container.classList.add("is-live");

      const tick = () => {
        const seconds = getTime();
        if (seconds === null) return;
        const frame = Math.min(Math.max(Math.round(seconds * envelope.fps), 0), lastFrame);
        const offset = frame * envelope.bands;
        for (let i = 0; i < used; i++) {
          const level = levelOf(envelope.data.charCodeAt(offset + i));
          // A floor rather than zero: a bar scaled to nothing vanishes, and a
          // row with gaps in it reads as broken rather than as quiet.
          bars[i].style.transform = `scaleY(${(0.08 + level * 0.92).toFixed(3)})`;
        }
      };

      tick();
      timer = window.setInterval(tick, 1000 / envelope.fps);
    });

    return () => {
      stopped = true;
      window.clearInterval(timer);
      // Back to the decorative animation, and the inline transforms cleared so
      // it has somewhere to move from.
      container.classList.remove("is-live");
      for (const bar of Array.from(container.children) as HTMLElement[]) {
        bar.style.transform = "";
      }
    };
  }, [containerRef, trackId, playing, getTime]);
}
